
YELLOW=`tput setaf 3`
RESET=`tput sgr 0` 

verify:
	@echo -e "\n\n${YELLOW}First version:${RESET}"
	uttamarin toy_1/protocol.spthy
	@echo -e "\n\n${YELLOW}Second version:${RESET}"
	uttamarin toy_2/protocol.spthy
	@echo -e "\n\n${YELLOW}Third version:${RESET}"
	uttamarin toy_3/protocol.spthy
	@echo -e "\n\n${YELLOW}Fourth version:${RESET}"
	uttamarin toy_4/protocol.spthy
